# Generated by Django 5.0 on 2024-11-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_ease_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='line_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='page_number',
        ),
    ]
